services:
  db:
    image: postgres:16.4  # Используем образ PostgreSQL версии 16.4
    environment:
      POSTGRES_DB: postgres   # Имя БД
      POSTGRES_USER: postgres  # Имя пользователя БД
      POSTGRES_PASSWORD: 3225   # Пароль для БД
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Сохраняем данные БД в volume

volumes:
  db_data: