# Используем официальный образ Python 3.11
FROM python:3.11-slim

#Устанавливаем рабочую директорию в контейнере
WORKDIR /Perekrestok

# Копируем содержимое репозитория в рабочую директорию
COPY . /Perekrestok

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Устанавливаем chromedriver и Google Chrome
RUN apt-get update && apt-get install -y wget unzip \
    && wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip \
    && unzip /tmp/chromedriver.zip -d /usr/local/bin/ \
    && rm /tmp/chromedriver.zip \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
    && apt-get update && apt-get install -y google-chrome-stable


# Указываем точку входа для выполнения
CMD ['python', 'main.py']