services:
  db:
    image: postgres:16.4  # Используем образ PostgreSQL версии 16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3225
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Сохраняем данные БД в volume

  app:
    build:
      context: .
      dockerfile: ./DockerFile
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db  # Имя хоста БД
      - DATABASE_PORT=5432  # Порт БД
      - DATABASE_NAME=postgres  # Имя БД
      - DATABASE_USER=postgres  # Имя пользователя БД
      - DATABASE_PASSWORD=3225  # Пароль для БД
    volumes:
      - .:/Perekrestok
    ports:
      - "8000:8000"  # Пробрасываем порт для приложения
    command: python main.py  # Команда для запуска приложения

volumes:
  db_data:
